services:
  db:
    image: postgres:15-alpine
    container_name: blog_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.docker

  web:
    build: .
    container_name: blog_web
    command: sh /app/entrypoint.sh
    ports:
      - "8001:8000"
    volumes:
      - static_volume:/app/staticfiles
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - blog_network
    restart: unless-stopped
    env_file:
      - .env.docker

volumes:
  postgres_data:
  static_volume:

networks:
  blog_network:
    driver: bridge
